version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - checkout
    
      - run:
          name: Greeting
          command: echo Hello, World
      
      - run:
          name: Print the Current File
          command: date
      
